### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 1br00** [kaanatmacaa/pdf-injection#1]
└─# python xss-pdf.py -o 2 -sc app.alert(2) 
zsh: unknown file attribute: 2
                                                                                                                                                            
┌──(root㉿kali)-[~/Desktop/uploadPDF/pdf-injection]
└─# python xss-pdf.py -o 1 -sc app.alert(2) 
zsh: unknown file attribute: 2

**Comment by kaanatmacaa** [comment]
In version 2, the issue has been resolved. Below is an example of how to use the script:
python xss-pdf.py -s "app.alert(2)"
